spring:
  profiles:
    active: dev
  application:
    name: xiaoMing
    upload-path: /home/echo/Data/work/xiaoming/upload
server:
  servlet:
    application-display-name: xiaoMing
    context-path: /api