server:
  port: 8081
spring:
  application:
    name: xiaoMing
  datasource:
    url: jdbc:mysql://localhost:3306/gak
    username: root
    password: 123456
    platform: mysql
  redis:
    host: 127.0.0.1
    database: 5
    password: 123456
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
logging:
  level:
    root: warn
  file: logs/xiaoMing.log

