server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gakDev?serverTimezone=GMT%2B8
    username: root
    password: 123456
    platform: mysql
  redis:
    host: 127.0.0.1
    database: 1
    password: 123456
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework.security: INFO
#    cn.echocow.xiaoming.service: DEBUG
security:
  oauth2:
    client:
      client-id: xiaoMing
      client-secret: $2a$10$Nww6ckqqJUg/botZzZDn1.8xZwTfW2n1mYE66lrUgn00KVzfe2T7C